### ISSUE TITLE
Doesn't build on iOS with Flutter 1.7.4-1.9.1+hotfix.2 stable (worked fine on Flutter 1.5)

### ISSUE THREAD

**Issue by vlkigdm** [AppsFlyerSDK/flutter_appsflyer_sdk#9]
Error log:

/Users/apple/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/appsflyer_sdk-1.1.3/ios/Classes/AppsflyerSdkPlugin.m:272:32: error: no visible @interface for 'FlutterViewController' declares the selector 'sendOnChannel:message:binaryReply:'
[flutterViewController sendOnChannel:channel message:dataFromDict binaryReply:^(NSData * _Nullable reply) {
~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
